replicaCount: 1

image:
  repository: linuxserver/grocy
  pullPolicy: Always
  port: 80
  env: {}

resources:
  arch: ~
  limits:
    cpu: 600m
    memory: 256Mi
  requests:
    cpu: 300m
    memory: 128Mi

volume:
  storageclass: ""
  accessMode: ReadWriteOnce
  path: /config
  claim: ~
  requests:
    storage: 10Gi

service:
  kind: "ClusterIP"
  port: 80
  protocol: TCP
  name: http

ingress:
  enabled: true
  hostname: example.com
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"

tolerations: []
