replicaCount: 1

image:
  repository: proctorlabs/rundeck
  pullPolicy: Always
  port: 4440
  env: {}

resources:
  arch: ~
  limits:
    cpu: 2000m
    memory: 1024Mi
  requests:
    cpu: 1000m
    memory: 256Mi

volume:
  storageclass: ""
  accessMode: ReadWriteOnce
  path: /rundeck
  requests:
    storage: 10Gi

service:
  kind: "ClusterIP"
  port: 80
  protocol: TCP
  name: http

ingress:
  enabled: true
  hostname: example.com
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"

tolerations: []
