replicaCount: 1

curl:
  enabled: yes
  schedule: '0 * * * *'
  url: 'http://cluster-local-host/'

image:
  repository: jc5x/firefly-iii:latest
  pullPolicy: Always
  port: 80
  env:
    app_name: FIREFLYNAME
    app_env: local
    app_debug: 'false'
    site_owner: ''
    app_key: ''
    tz: America/New_York
    app_url: URL
    trusted_proxies: ''
    log_channel: daily
    app_log_level: notice
    db_connection: pgsql
    db_host: ''
    db_port: '5432'
    db_database: firefly
    db_username: ''
    db_password: ''
    pgsql_ssl_mode: prefer
    pgsql_ssl_root_cert: "null"
    pgsql_ssl_cert: "null"
    pgsql_ssl_key: "null"
    pgsql_ssl_crl_file: "null"
    cache_driver: file
    session_driver: file
    cookie_path: "/"
    cookie_domain: ''
    cookie_secure: "false"
    mail_driver: log
    send_registration_mail: "false"
    send_error_message: "false"
    send_report_journals: "false"
    login_provider: ldap
    adldap_auto_connect: "true"
    adldap_port: "389"
    adldap_timeout: "5"
    adldap_follow_refferals: "false"
    adldap_use_ssl: "false"
    adldap_use_tls: "false"
    adldap_password_sync: "false"
    adldap_login_fallback: "false"
    adldap_controllers: ''
    adldap_connection_scheme: ''
    adldap_basedn: ''
    adldap_admin_username: ''
    adldap_admin_password: ''
    adldap_discover_field: ''
    adldap_account_prefix: ''
    adldap_account_suffix: ''
    adldap_auth_field: ''
    adldap_sync_field: ''
    disable_frame_header: "false"

resources:
  arch: ~
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

volume:
  storageclass: ""
  accessMode: ReadWriteOnce
  path: /data
  requests:
    storage: 10Gi

service:
  kind: "ClusterIP"
  port: 80
  protocol: TCP
  name: http

ingress:
  enabled: true
  hostname: example.com
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"

tolerations: []

nodeselector: {}
