replicaCount: 1

image:
  repository: kruptein/planarally
  pullPolicy: Always
  port: 8000
  env: {}

resources:
  arch: amd64
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

volume:
  storageclass: ""
  accessMode: ReadWriteOnce
  path: /planarally/static/assets
  requests:
    storage: 10Gi

service:
  kind: "ClusterIP"
  port: 80
  protocol: TCP
  name: http

ingress:
  enabled: true
  hostname: example.com
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
