replicaCount: 1

image:
  repository: robertslando/zwave2mqtt:latest
  pullPolicy: Always
  port: 80
  env: {}

resources:
  arch: ~
  limits:
    cpu: 2000m
    memory: 512Mi
  requests:
    cpu: 1000m
    memory: 128Mi

volume:
  storageclass: ""
  accessMode: ReadWriteOnce
  path: /data
  requests:
    storage: 10Gi

service:
  kind: "ClusterIP"
  port: 80
  protocol: TCP
  name: http

ingress:
  enabled: true
  hostname: example.com
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"

device:
  path: /dev/ttyUSB0

tolerations: []
