replicaCount: 1

image:
  repository: mayanedms/mayanedms:3.4.10
  pullPolicy: Always
  port: 80
  env: {}

resources:
  arch: amd64
  limits:
    cpu: 3000m
    memory: 2048Mi
  requests:
    cpu: 1500m
    memory: 1024Mi

volume:
  storageclass: ""
  accessMode: ReadWriteOnce
  path: /var/lib/mayan
  requests:
    storage: 10Gi

service:
  kind: "ClusterIP"
  port: 80
  protocol: TCP
  name: http

ingress:
  enabled: true
  hostname: mayan-edms.example.com
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
