name: publish-charts

on:
  push:
    branches: [master]

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish Helm charts
        uses: proctorlabs/charts@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
